### ISSUE TITLE
Payment method not found

### ISSUE THREAD

**Issue by endlichstudios** [joomdonation/os_eb_redirect#1]
I get a "0 - Payment method not found" when using the payment_confirm url "option=com_eventbooking&task=payment_confirm&name=os_payment_plugin_name", not matter which plugin name I use. I've tried with my custom plugin's name as well as the os_paypal plugin and get the same results. 
![12-14-2017 2-37-45 pm](https://user-images.githubusercontent.com/4307235/34010947-6992c538-e0dc-11e7-8505-9ede487d60ac.jpg)

**Comment by joomdonation** [comment]
Hi

You need to change os_payment_plugin_name to name of the payment plugin which you developed (the class name)

For example, with os_paypal, it is name=os_paypal

**Comment by endlichstudios** [comment]
I tried that. I used my plug in name and get that message. I also used the os_paypal name and get the same results. Any other ideas?
![12-15-2017 7-59-51 am](https://user-images.githubusercontent.com/4307235/34043219-11554e3a-e16e-11e7-9f8f-e7123dc1b519.jpg)
![12-15-2017 7-59-07 am](https://user-images.githubusercontent.com/4307235/34043220-11672c04-e16e-11e7-8a4d-921ca1e850ef.jpg)
![12-15-2017 7-58-46 am](https://user-images.githubusercontent.com/4307235/34043221-11736c9e-e16e-11e7-8ea9-80309e937d98.jpg)

**Comment by endlichstudios** [comment]
After reviewing the code, it seems that the url should really be:
"option=com_eventbooking&task=payment_confirm&**payment_method**=os_payment_plugin_name"
instead of 
"option=com_eventbooking&task=payment_confirm&**name**=os_payment_plugin_name"

Would you agree with this solution?

**Comment by joomdonation** [comment]
Hi

Yes. The URL should be option=com_eventbooking&task=payment_confirm&payment_method=os_payment_plugin_name

Sorry for the typo, and lately response. I was too busy last week to update our order system to be able to update our website to use PHP 7
